### PR TITLE
underwater_envs will contain envs from mmt surveys

### PR DESCRIPTION
**Pull request by ignaciotb**
Success! :dancer:

### CODE REVIEW

**Comment by nilsbore** [comment]
@ignaciotb Have you tried it out in gazebo?

**Comment by ignaciotb** [comment]
yes, have you?
It should work without modifying the paths, but it's just a prove of concept, the env isn't finished

**Comment by nilsbore** [comment]
@ignaciotb Can you make another PR which removes eveything but the environment you created? We want to remove the launch files for everything but the skytteren world.

**Comment by nilsbore** [comment]
Nice work btw, the skytteren environment works nicely!

**Pull request merged**
